server:
  port: 8081

spring:
  profiles:
    # 配置中心从本地文件读取配置
    active: native
  cloud:
    config:
      server:
        native:
          # 本地文件所在位置
          search-locations: D:/git/spring-cloud/config