# Spring Cloud Eureka 配置文件详解：https://www.cnblogs.com/rickiyang/p/11802441.html
spring:
  application:
    name: eureka-client-student-service

server:
  port: 8098

eureka:
  instance:
    hostname: localhost
    # 服务续约任务调用间隔时间，默认30秒
    # client 每隔30秒向 server 上报自己状态，避免被 server 剔除
    lease-renewal-interval-in-seconds: 5
    # 服务时效时间，默认90秒
    # 当 server 90秒内没有收到 client 的注册信息时，会将该节点剔除
    lease-expiration-duration-in-seconds: 10
  client:
    service-url:
      # 默认服务注册中心地址，多个用","隔开
      defaultZone: http://${eureka.instance.hostname}:8761/eureka
    # 需要 actuator
    healthcheck:
      enabled: true
