spring:
  application:
    name: gateway
  # yml 配置 routes
  cloud:
    gateway:
      routes:
        - predicates:
            - Path=/student/**
          filters:
            - StripPrefix=1
          uri: "http://localhost:8090/"
server:
  port: 8080
